import React, { useState } from 'react';
import { useData, Quotation } from '../../context/DataContext';
import { useAuth } from '../../context/AuthContext';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Textarea } from '../ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/card';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '../ui/dialog';
import { Badge } from '../ui/badge';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../ui/table';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../ui/tabs';
import { FileText, Plus, Edit, Download, Eye, Send, CheckCircle, XCircle, Clock, User, Building, Calendar, DollarSign } from 'lucide-react';

export function QuotationManagement() {
  const { quotations, addQuotation, updateQuotation, deleteQuotation, customers, packages } = useData();
  const { user } = useAuth();
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [editingQuotation, setEditingQuotation] = useState<Quotation | null>(null);
  const [viewingQuotation, setViewingQuotation] = useState<Quotation | null>(null);
  const [formData, setFormData] = useState({
    customerId: '',
    packageId: '',
    totalPrice: 0,
    discount: 0,
    finalPrice: 0,
    validUntil: '',
    status: 'DRAFT' as 'DRAFT' | 'SENT' | 'APPROVED' | 'REJECTED',
    notes: ''
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    const quotationData = {
      ...formData,
      createdBy: user?.id || '',
      createdAt: new Date().toISOString(),
      finalPrice: formData.totalPrice - formData.discount
    };
    
    if (editingQuotation) {
      updateQuotation(editingQuotation.id, quotationData);
    } else {
      addQuotation(quotationData);
    }
    
    resetForm();
    setIsDialogOpen(false);
  };

  const resetForm = () => {
    setFormData({
      customerId: '',
      packageId: '',
      totalPrice: 0,
      discount: 0,
      finalPrice: 0,
      validUntil: '',
      status: 'DRAFT',
      notes: ''
    });
    setEditingQuotation(null);
  };

  const handleEdit = (quotation: Quotation) => {
    setEditingQuotation(quotation);
    setFormData({
      customerId: quotation.customerId,
      packageId: quotation.packageId,
      totalPrice: quotation.totalPrice,
      discount: quotation.discount,
      finalPrice: quotation.finalPrice,
      validUntil: quotation.validUntil.split('T')[0], // Format for date input
      status: quotation.status,
      notes: quotation.notes
    });
    setIsDialogOpen(true);
  };

  const handleStatusChange = (quotationId: string, newStatus: 'DRAFT' | 'SENT' | 'APPROVED' | 'REJECTED') => {
    updateQuotation(quotationId, { status: newStatus });
  };

  const handlePackageChange = (packageId: string) => {
    const selectedPackage = packages.find(p => p.id === packageId);
    if (selectedPackage) {
      setFormData({
        ...formData,
        packageId,
        totalPrice: selectedPackage.basePrice,
        finalPrice: selectedPackage.basePrice - formData.discount
      });
    }
  };

  const handleDiscountChange = (discount: number) => {
    setFormData({
      ...formData,
      discount,
      finalPrice: formData.totalPrice - discount
    });
  };

  const generatePDF = (quotation: Quotation) => {
    const customer = customers.find(c => c.id === quotation.customerId);
    const pkg = packages.find(p => p.id === quotation.packageId);
    
    // Simple PDF generation simulation
    const pdfContent = `
TRAVEL QUOTATION

Customer: ${customer?.name}
${customer?.type === 'B2B_CLIENT' ? `Company: ${customer.companyName}` : ''}
Email: ${customer?.email}
Phone: ${customer?.phone}

Package: ${pkg?.name}
Duration: ${pkg?.duration} days
Description: ${pkg?.description}

PRICING:
Base Price: $${quotation.totalPrice}
Discount: $${quotation.discount}
Final Price: $${quotation.finalPrice}

Valid Until: ${new Date(quotation.validUntil).toLocaleDateString()}
Status: ${quotation.status}

Notes: ${quotation.notes}

Generated by: ${user?.businessName}
Date: ${new Date().toLocaleDateString()}
    `;
    
    // Create and download PDF simulation
    const blob = new Blob([pdfContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `quotation-${quotation.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'APPROVED':
        return <CheckCircle className="w-4 h-4 text-green-600" />;
      case 'REJECTED':
        return <XCircle className="w-4 h-4 text-red-600" />;
      case 'SENT':
        return <Send className="w-4 h-4 text-blue-600" />;
      default:
        return <Clock className="w-4 h-4 text-gray-600" />;
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'APPROVED':
        return 'bg-green-100 text-green-800';
      case 'REJECTED':
        return 'bg-red-100 text-red-800';
      case 'SENT':
        return 'bg-blue-100 text-blue-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  const draftQuotations = quotations.filter(q => q.status === 'DRAFT');
  const sentQuotations = quotations.filter(q => q.status === 'SENT');
  const approvedQuotations = quotations.filter(q => q.status === 'APPROVED');

  const QuotationTable = ({ quotations }: { quotations: Quotation[] }) => (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead>Customer</TableHead>
          <TableHead>Package</TableHead>
          <TableHead>Amount</TableHead>
          <TableHead>Valid Until</TableHead>
          <TableHead>Status</TableHead>
          <TableHead>Actions</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {quotations.map((quotation) => {
          const customer = customers.find(c => c.id === quotation.customerId);
          const pkg = packages.find(p => p.id === quotation.packageId);
          
          return (
            <TableRow key={quotation.id}>
              <TableCell>
                <div className="flex items-center space-x-2">
                  {customer?.type === 'B2B_CLIENT' ? (
                    <Building className="w-4 h-4" />
                  ) : (
                    <User className="w-4 h-4" />
                  )}
                  <div>
                    <p className="text-sm">{customer?.name}</p>
                    {customer?.companyName && (
                      <p className="text-xs text-gray-600">{customer.companyName}</p>
                    )}
                  </div>
                </div>
              </TableCell>
              <TableCell>
                <div>
                  <p className="text-sm">{pkg?.name}</p>
                  <p className="text-xs text-gray-600">{pkg?.duration} days</p>
                </div>
              </TableCell>
              <TableCell>
                <div>
                  <p className="text-sm">${quotation.finalPrice.toLocaleString()}</p>
                  {quotation.discount > 0 && (
                    <p className="text-xs text-gray-600">
                      Discount: ${quotation.discount}
                    </p>
                  )}
                </div>
              </TableCell>
              <TableCell>
                <div className="flex items-center space-x-1">
                  <Calendar className="w-3 h-3" />
                  <span className="text-sm">
                    {new Date(quotation.validUntil).toLocaleDateString()}
                  </span>
                </div>
              </TableCell>
              <TableCell>
                <div className="flex items-center space-x-2">
                  {getStatusIcon(quotation.status)}
                  <Badge className={getStatusColor(quotation.status)}>
                    {quotation.status}
                  </Badge>
                </div>
              </TableCell>
              <TableCell>
                <div className="flex space-x-1">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setViewingQuotation(quotation)}
                  >
                    <Eye className="w-3 h-3" />
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => handleEdit(quotation)}
                  >
                    <Edit className="w-3 h-3" />
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => generatePDF(quotation)}
                  >
                    <Download className="w-3 h-3" />
                  </Button>
                  {quotation.status === 'DRAFT' && (
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleStatusChange(quotation.id, 'SENT')}
                    >
                      <Send className="w-3 h-3" />
                    </Button>
                  )}
                </div>
              </TableCell>
            </TableRow>
          );
        })}
      </TableBody>
    </Table>
  );

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center space-x-2">
                <FileText className="w-5 h-5" />
                <span>Quotation Management</span>
              </CardTitle>
              <CardDescription>
                Create and manage travel quotations for customers
              </CardDescription>
            </div>
            <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
              <DialogTrigger asChild>
                <Button onClick={resetForm}>
                  <Plus className="w-4 h-4 mr-2" />
                  Create Quotation
                </Button>
              </DialogTrigger>
              <DialogContent className="max-w-2xl">
                <DialogHeader>
                  <DialogTitle>
                    {editingQuotation ? 'Edit Quotation' : 'Create New Quotation'}
                  </DialogTitle>
                  <DialogDescription>
                    {editingQuotation ? 'Update quotation details' : 'Create a new quotation for a customer'}
                  </DialogDescription>
                </DialogHeader>
                <form onSubmit={handleSubmit}>
                  <div className="space-y-4">
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <Label htmlFor="customer">Customer</Label>
                        <Select
                          value={formData.customerId}
                          onValueChange={(value) => setFormData({ ...formData, customerId: value })}
                        >
                          <SelectTrigger>
                            <SelectValue placeholder="Select customer" />
                          </SelectTrigger>
                          <SelectContent>
                            {customers.map((customer) => (
                              <SelectItem key={customer.id} value={customer.id}>
                                {customer.name}
                                {customer.companyName && ` (${customer.companyName})`}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                      <div>
                        <Label htmlFor="package">Package</Label>
                        <Select
                          value={formData.packageId}
                          onValueChange={handlePackageChange}
                        >
                          <SelectTrigger>
                            <SelectValue placeholder="Select package" />
                          </SelectTrigger>
                          <SelectContent>
                            {packages.map((pkg) => (
                              <SelectItem key={pkg.id} value={pkg.id}>
                                {pkg.name} - ${pkg.basePrice}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                    </div>

                    <div className="grid grid-cols-3 gap-4">
                      <div>
                        <Label htmlFor="totalPrice">Total Price ($)</Label>
                        <Input
                          id="totalPrice"
                          type="number"
                          value={formData.totalPrice}
                          onChange={(e) => setFormData({ 
                            ...formData, 
                            totalPrice: parseInt(e.target.value),
                            finalPrice: parseInt(e.target.value) - formData.discount
                          })}
                          required
                        />
                      </div>
                      <div>
                        <Label htmlFor="discount">Discount ($)</Label>
                        <Input
                          id="discount"
                          type="number"
                          value={formData.discount}
                          onChange={(e) => handleDiscountChange(parseInt(e.target.value))}
                        />
                      </div>
                      <div>
                        <Label htmlFor="finalPrice">Final Price ($)</Label>
                        <Input
                          id="finalPrice"
                          type="number"
                          value={formData.finalPrice}
                          readOnly
                          className="bg-gray-100"
                        />
                      </div>
                    </div>

                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <Label htmlFor="validUntil">Valid Until</Label>
                        <Input
                          id="validUntil"
                          type="date"
                          value={formData.validUntil}
                          onChange={(e) => setFormData({ ...formData, validUntil: e.target.value })}
                          required
                        />
                      </div>
                      <div>
                        <Label htmlFor="status">Status</Label>
                        <Select
                          value={formData.status}
                          onValueChange={(value: 'DRAFT' | 'SENT' | 'APPROVED' | 'REJECTED') => 
                            setFormData({ ...formData, status: value })
                          }
                        >
                          <SelectTrigger>
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="DRAFT">Draft</SelectItem>
                            <SelectItem value="SENT">Sent</SelectItem>
                            <SelectItem value="APPROVED">Approved</SelectItem>
                            <SelectItem value="REJECTED">Rejected</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                    </div>

                    <div>
                      <Label htmlFor="notes">Notes</Label>
                      <Textarea
                        id="notes"
                        value={formData.notes}
                        onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                        rows={3}
                        placeholder="Additional notes or terms"
                      />
                    </div>
                  </div>
                  <DialogFooter className="mt-6">
                    <Button type="button" variant="outline" onClick={() => setIsDialogOpen(false)}>
                      Cancel
                    </Button>
                    <Button type="submit">
                      {editingQuotation ? 'Update' : 'Create'} Quotation
                    </Button>
                  </DialogFooter>
                </form>
              </DialogContent>
            </Dialog>
          </div>
        </CardHeader>
        <CardContent>
          <Tabs defaultValue="all" className="space-y-4">
            <TabsList>
              <TabsTrigger value="all">All ({quotations.length})</TabsTrigger>
              <TabsTrigger value="draft">Draft ({draftQuotations.length})</TabsTrigger>
              <TabsTrigger value="sent">Sent ({sentQuotations.length})</TabsTrigger>
              <TabsTrigger value="approved">Approved ({approvedQuotations.length})</TabsTrigger>
            </TabsList>
            
            <TabsContent value="all">
              <QuotationTable quotations={quotations} />
            </TabsContent>
            
            <TabsContent value="draft">
              <QuotationTable quotations={draftQuotations} />
            </TabsContent>
            
            <TabsContent value="sent">
              <QuotationTable quotations={sentQuotations} />
            </TabsContent>
            
            <TabsContent value="approved">
              <QuotationTable quotations={approvedQuotations} />
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>

      {/* Quotation Preview Dialog */}
      {viewingQuotation && (
        <Dialog open={!!viewingQuotation} onOpenChange={() => setViewingQuotation(null)}>
          <DialogContent className="max-w-2xl">
            <DialogHeader>
              <DialogTitle>Quotation Preview</DialogTitle>
            </DialogHeader>
            <div className="space-y-4">
              {(() => {
                const customer = customers.find(c => c.id === viewingQuotation.customerId);
                const pkg = packages.find(p => p.id === viewingQuotation.packageId);
                
                return (
                  <div className="space-y-4">
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <h4>Customer Information</h4>
                        <p>{customer?.name}</p>
                        {customer?.companyName && <p>{customer.companyName}</p>}
                        <p className="text-sm text-gray-600">{customer?.email}</p>
                      </div>
                      <div>
                        <h4>Package Details</h4>
                        <p>{pkg?.name}</p>
                        <p className="text-sm text-gray-600">{pkg?.duration} days</p>
                        <p className="text-sm text-gray-600">{pkg?.description}</p>
                      </div>
                    </div>
                    
                    <div>
                      <h4>Pricing</h4>
                      <div className="space-y-1">
                        <div className="flex justify-between">
                          <span>Base Price:</span>
                          <span>${viewingQuotation.totalPrice}</span>
                        </div>
                        <div className="flex justify-between">
                          <span>Discount:</span>
                          <span>-${viewingQuotation.discount}</span>
                        </div>
                        <div className="flex justify-between border-t pt-1">
                          <span>Final Price:</span>
                          <span>${viewingQuotation.finalPrice}</span>
                        </div>
                      </div>
                    </div>
                    
                    {viewingQuotation.notes && (
                      <div>
                        <h4>Notes</h4>
                        <p className="text-sm text-gray-600">{viewingQuotation.notes}</p>
                      </div>
                    )}
                  </div>
                );
              })()}
            </div>
            <DialogFooter>
              <Button onClick={() => generatePDF(viewingQuotation)}>
                <Download className="w-4 h-4 mr-2" />
                Download PDF
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}
    </div>
  );
}